[package]
name = "greenis"
version = "0.1.0"
authors = ["roger <rogerduran@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis-protocol = "0.1.2"
bytes = "0.4.12"
